'import warnings' failed; traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.12/warnings.py", line 585, in <module>
    _processoptions(sys.warnoptions)
  File "/usr/lib/python3.12/warnings.py", line 209, in _processoptions
    _setoption(arg)
  File "/usr/lib/python3.12/warnings.py", line 225, in _setoption
    import re
  File "/usr/lib/python3.12/re/__init__.py", line 338, in <module>
    import copyreg
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1601, in find_spec
  File "<frozen importlib._bootstrap_external>", line 147, in _path_stat
KeyboardInterrupt
